### ISSUE TITLE
Discuss whether to rely on events vs forcing updates for changes in the web3 context

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-network.js#10]
Currently, the web3 context exposes event handlers for reacting to changes in its properties, such as networks or accounts. This is used like:

```js
web3Context.on(Web3Context.NetworkIdChangedEventName, (networkId, networkName) => {
  setNetwork({ networkId, networkName });
});
```

On the other hand, @frangio thought about forcing a react component update whenever there is a change, so the user just renders the web3context properties, and the component where they are used gets re-rendered when they change, as usual. This requires the following change in the hook code:

```ts
  const [context, setContext] = useState(() => new Web3Context(provider, options));
  const forceUpdate = useForceUpdate();

  // Causes components down the tree to re-render when any of the Web3Context properties change.
  useEffect((): (() => void) => {
    context.on('NetworkIdChanged', forceUpdate);
    context.on('AccountsChanged', forceUpdate);
    context.on('ConnectionChanged', forceUpdate);
    return (): void => {
      context.off('NetworkIdChanged', forceUpdate);
      context.off('AccountsChanged', forceUpdate);
      context.off('ConnectionChanged', forceUpdate);
    }
  }, [context]);
```

We should discuss which of the two approaches we want to go with in a future version.

**Comment by frangio** [comment]
If we don't do this, an app that wants to keep track of, for example, accounts and connected status, is forced to write the event listeners, which (done properly) is not very nice using React hooks:

```javascript
function App() {
  const signKey = useEphemeralKey();
  const web3Context = useWeb3Injected({ gsn: { signKey } });

  useEffect(() => {
    web3Context.requestAuth()
  }, []);

  const [connected, _setConnected] = useState(false);
  const setConnected = useCallback(name => _setConnected(name), []);

  const [accounts, _setAccounts] = useState([]);
  const setAccounts = useCallback(name => _setAccounts(name), []);

  useEffect(() => {
    web3Context.on(Web3Context.ConnectionChangedEventName, setConnected);
    web3Context.on(Web3Context.AccountsChangedEventName, setAccounts);
    return () => {
      web3Context.off(Web3Context.ConnectionChangedEventName, setConnected);
      web3Context.off(Web3Context.AccountsChangedEventName, setAccounts);
    };
  }, [web3Context]);
```

There is a lot of boilerplate that could be removed. I think we should explore this in depth to provide the best possible DX to users.

**Comment by ylv-io** [comment]
Hey @frangio! That is a nice idea and I agree that we should reduce boilerplate to minimum!

**Comment by ylv-io** [comment]
We decided to use forceupdate to keep it functional react style.
