### ISSUE TITLE
Trouble installing on windows

### ISSUE THREAD

**Issue by amcassetti** [OpenZeppelin/openzeppelin-network.js#26]
npm install results in the following error:

`'ln' is not recognized as an internal or external command, operable program or batch file.`

**Comment by abcoathup** [comment]
Hi @amcassetti,

I'm sorry you ran into this issue.

OpenZeppelin Network.js uses `preinstall` to create a symlink for React.
`ln` doesn't exist on Windows.
https://github.com/OpenZeppelin/openzeppelin-network.js/blob/master/package.json#L14

You can try to import hooks directly from `@openzeppelin/network/lib/react`

Example:
```
import { useWeb3Network, useEphemeralKey, useWeb3Injected } from '@openzeppelin/network/lib/react';
```
According to this [StackOverflow answer](https://stackoverflow.com/questions/894430/creating-hard-and-soft-links-using-powershell/34905638#34905638), you can create a soft link using the [`New-Item`](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/New-Item?view=powershell-5.1) cmdlet.
(Thanks @nventuro: https://github.com/OpenZeppelin/starter-kit-gsn/issues/44#issuecomment-571235053)

Alternatively, you could use Windows Subsystem for Linux, this is what I use on Windows 10.

**Comment by amcassetti** [comment]
Thanks for quick response! Installing using the gitbash console worked
