### ISSUE TITLE
Broken Symlink in @openzeppelin/network@0.4.0 npm package

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-network.js#29]
There is a broken symlink after installing `@openzeppelin/network@0.4.0` 

<img width="509" alt="OpenZeppelin Network js react" src="https://user-images.githubusercontent.com/28278242/74903714-e6aab580-53fd-11ea-8103-4bac36c97872.png">

The symlink is created in a preinstall, but there is no `react` directory in `./lib`
```
"preinstall": "ln -s ./lib/react ./react"
```
Reported by a community member in the forum: https://forum.openzeppelin.com/t/broken-symlink-in-openzeppelin-network-0-4-0-npm-package/2309

Workaround is to uninstall version `0.4.0` and install the previous version `0.3.0`: 
`npm i @openzeppelin/network@0.3.0`

**Comment by ylv-io** [comment]
For some reason TypeScript hasn't compiled React folder into latest build. Fixed now. Starter Kit is updated as well!
