### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by ravidsrk** [OpenZeppelin/openzeppelin-network.js#7]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use.

**Comment by frangio** [comment]
Hey there. Thanks for the suggestion. :slightly_smiling_face: No need to close the issue.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-network.js/commit/038fbf863d6212b350da9a0e3c22a2132dbed935.
